title: Chen-Wei (Chaney) Hsu
logo: /assets/img/profile-pic.jpg
description: I am a passionate and driven Master's in Applied Data Analytics student at Boston University with a strong foundation in statistics and economics. My academic and research journey has been fueled by curiosity and a commitment to advancing solutions in interdisciplinary fields.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
